### ISSUE TITLE
FooterCreds does not extend Brick

### ISSUE THREAD

**Issue by craigsimps** [gamajo/genesis-theme-toolkit#1]
FooterCreds was added in commit 68398d8, but it does not extend the base Brick class.

**Comment by craigsimps** [comment]
Actually with the change to extend Brick, ConfigTrait and the constructor should also be removed I think.

**Comment by GaryJones** [comment]
Thanks - this is one of the later ones to get added in after I'd moved the rest into its own package, so I guess I didn't fully merge it like the others.

Thanks!
